# Generated by Django 5.2 on 2025-04-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('data_reembolso', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
